image: gcc

stages:
  - build

init:
  stage: .pre
  script:
    - echo "This is the initialization of the CI/CD"


cmake:
  stage: build
  script:
    - mkdir build && cd build
    - apt-get install cmake
    - cmake ..
    - make
